# Generated by Django 4.0.3 on 2024-02-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_alter_appointment_technician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, unique=True),
        ),
    ]
